# Generated by Django 4.2.6 on 2023-11-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKVC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='carousel_images/')),
            ],
        ),
    ]
