# Generated by Django 4.2.6 on 2023-11-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKVC', '0002_carouselslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
