# Generated by Django 4.2.6 on 2023-11-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKVC', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=255)),
                ('Customer_email', models.EmailField(max_length=254)),
                ('Customer_age', models.CharField(max_length=10)),
                ('service_type', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
