# Generated by Django 4.2.6 on 2023-11-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKVC', '0005_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Customer_age',
        ),
        migrations.AddField(
            model_name='appointment',
            name='mobile_number',
            field=models.CharField(default=1223, max_length=15),
            preserve_default=False,
        ),
    ]
