# Generated by Django 4.2.6 on 2024-02-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKVC', '0007_remove_project_image_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
