# Generated by Django 4.2.6 on 2024-04-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SKVC', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
